"""New Migration

Revision ID: 3917fe76c54c
Revises: 7f23dae708a4
Create Date: 2025-01-17 09:08:06.428520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3917fe76c54c'
down_revision: Union[str, None] = '7f23dae708a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('matched_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'matched_id')
    # ### end Alembic commands ###
