"""New Migration

Revision ID: 7f23dae708a4
Revises: cc088925baa5
Create Date: 2025-01-17 08:58:58.875978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f23dae708a4'
down_revision: Union[str, None] = 'cc088925baa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_matched', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('HOST_FAMILY', 'DISPLACED_FAMILY', name='usertypeenum'), nullable=False),
    sa.Column('has_pets', sa.Boolean(), nullable=True),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.drop_index('ix_displaced_families_id', table_name='displaced_families')
    op.drop_index('ix_displaced_families_name', table_name='displaced_families')
    op.drop_table('displaced_families')
    op.drop_index('ix_host_families_id', table_name='host_families')
    op.drop_index('ix_host_families_name', table_name='host_families')
    op.drop_table('host_families')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_families',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_of_people', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pet_friendly', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('matched', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='host_families_pkey')
    )
    op.create_index('ix_host_families_name', 'host_families', ['name'], unique=False)
    op.create_index('ix_host_families_id', 'host_families', ['id'], unique=False)
    op.create_table('displaced_families',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_of_family_members', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('matched', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_pets', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='displaced_families_pkey')
    )
    op.create_index('ix_displaced_families_name', 'displaced_families', ['name'], unique=False)
    op.create_index('ix_displaced_families_id', 'displaced_families', ['id'], unique=False)
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
