"""New Migration

Revision ID: a48ad17786db
Revises: 0688cb50c9ed
Create Date: 2025-01-16 22:06:47.220776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48ad17786db'
down_revision: Union[str, None] = '0688cb50c9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('displaced_families', sa.Column('has_pets', sa.Boolean(), nullable=True))
    op.drop_column('displaced_families', 'number_of_pets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('displaced_families', sa.Column('number_of_pets', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('displaced_families', 'has_pets')
    # ### end Alembic commands ###
